# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fx2ptQV6-2LAmCpfqRcX5jkKR70FWLP1
"""

"""
SCRIPT 1: TRAIN AND FINE-TUNE MODEL
This script trains the model on train.csv and saves the fine-tuned model
"""

# ============================================================================
# STEP 1: Install Required Libraries
# ============================================================================
# !pip install transformers datasets torch pandas numpy scikit-learn sentencepiece accelerate -q

# ============================================================================
# STEP 2: Import Libraries
# ============================================================================
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel, get_linear_schedule_with_warmup
from torch.optim import AdamW
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')
from tqdm.auto import tqdm
import gc
import os
import json

# Set random seeds for reproducibility
def set_seed(seed=42):
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(42)

# ============================================================================
# STEP 3: Configuration
# ============================================================================
class Config:
    # Model configuration
    model_name = "sentence-transformers/all-MiniLM-L6-v2"
    max_length = 256
    batch_size = 32
    learning_rate = 2e-5
    num_epochs = 15
    warmup_steps = 500
    dropout = 0.3

    # Paths
    train_path = "train.csv"
    model_save_path = "finetuned_price_model"

    # Device
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

config = Config()
print(f"Using device: {config.device}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# ============================================================================
# STEP 4: Load and Preprocess Data
# ============================================================================
print("\n" + "="*70)
print("LOADING AND PREPROCESSING DATA")
print("="*70)

train_df = pd.read_csv(config.train_path)
print(f"Train shape: {train_df.shape}")
print(f"Columns: {train_df.columns.tolist()}")
print(f"\nFirst few rows:")
print(train_df.head(2))
print(f"\nPrice statistics:")
print(train_df['price'].describe())

# Handle missing values
train_df['catalog_content'] = train_df['catalog_content'].fillna("No description available")

# Clean text
def clean_text(text):
    text = str(text)
    text = text.replace('\n', ' ').replace('\r', ' ')
    text = ' '.join(text.split())
    return text

train_df['catalog_content'] = train_df['catalog_content'].apply(clean_text)

# Apply log transformation to prices for better training stability
print("\nApplying log transformation to prices...")
train_df['log_price'] = np.log1p(train_df['price'])

print(f"Log-transformed price statistics:")
print(train_df['log_price'].describe())

# Split data into train and validation
train_texts, val_texts, train_prices, val_prices = train_test_split(
    train_df['catalog_content'].values,
    train_df['log_price'].values,
    test_size=0.1,
    random_state=42
)

print(f"\nTrain samples: {len(train_texts)}")
print(f"Validation samples: {len(val_texts)}")

# ============================================================================
# STEP 5: Create Dataset Class
# ============================================================================
class PriceDataset(Dataset):
    def __init__(self, texts, prices, tokenizer, max_length):
        self.texts = texts
        self.prices = prices
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = str(self.texts[idx])
        price = self.prices[idx]

        encoding = self.tokenizer(
            text,
            max_length=self.max_length,
            padding='max_length',
            truncation=True,
            return_tensors='pt'
        )

        return {
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'price': torch.tensor(price, dtype=torch.float)
        }

# ============================================================================
# STEP 6: Create Model Architecture
# ============================================================================
class PricePredictionModel(nn.Module):
    def __init__(self, model_name, dropout=0.3):
        super(PricePredictionModel, self).__init__()
        self.transformer = AutoModel.from_pretrained(model_name)
        self.dropout = nn.Dropout(dropout)

        # Regression head with multiple layers
        hidden_size = self.transformer.config.hidden_size
        self.regressor = nn.Sequential(
            nn.Linear(hidden_size, 512),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(512, 256),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(256, 1)
        )

    def forward(self, input_ids, attention_mask):
        outputs = self.transformer(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        # Use [CLS] token representation
        pooled_output = outputs.last_hidden_state[:, 0, :]
        pooled_output = self.dropout(pooled_output)

        # Predict price
        price = self.regressor(pooled_output)
        return price

# ============================================================================
# STEP 7: Initialize Model and Tokenizer
# ============================================================================
print("\n" + "="*70)
print("INITIALIZING MODEL")
print("="*70)

print(f"Loading pre-trained model: {config.model_name}")
tokenizer = AutoTokenizer.from_pretrained(config.model_name)
model = PricePredictionModel(config.model_name, dropout=config.dropout)
model.to(config.device)

total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"Total parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")

# ============================================================================
# STEP 8: Create Data Loaders
# ============================================================================
print("\nCreating data loaders...")
train_dataset = PriceDataset(train_texts, train_prices, tokenizer, config.max_length)
val_dataset = PriceDataset(val_texts, val_prices, tokenizer, config.max_length)

train_loader = DataLoader(train_dataset, batch_size=config.batch_size, shuffle=True, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=config.batch_size, shuffle=False, num_workers=2)

print(f"Train batches: {len(train_loader)}")
print(f"Validation batches: {len(val_loader)}")

# ============================================================================
# STEP 9: Training Setup
# ============================================================================
criterion = nn.MSELoss()
optimizer = AdamW(model.parameters(), lr=config.learning_rate, weight_decay=0.01)

total_steps = len(train_loader) * config.num_epochs
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=config.warmup_steps,
    num_training_steps=total_steps
)

print(f"\nTotal training steps: {total_steps}")
print(f"Warmup steps: {config.warmup_steps}")

# ============================================================================
# STEP 10: Training Function
# ============================================================================
def train_epoch(model, loader, optimizer, criterion, scheduler, device):
    model.train()
    total_loss = 0
    progress_bar = tqdm(loader, desc="Training")

    for batch in progress_bar:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        prices = batch['price'].to(device).unsqueeze(1)

        optimizer.zero_grad()

        predictions = model(input_ids, attention_mask)
        loss = criterion(predictions, prices)

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

        total_loss += loss.item()
        progress_bar.set_postfix({'loss': f'{loss.item():.4f}'})

    return total_loss / len(loader)

# ============================================================================
# STEP 11: Validation Function
# ============================================================================
def validate(model, loader, criterion, device):
    model.eval()
    total_loss = 0
    all_predictions = []
    all_actuals = []

    with torch.no_grad():
        for batch in tqdm(loader, desc="Validation"):
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            prices = batch['price'].to(device).unsqueeze(1)

            predictions = model(input_ids, attention_mask)
            loss = criterion(predictions, prices)

            total_loss += loss.item()
            all_predictions.extend(predictions.cpu().numpy())
            all_actuals.extend(prices.cpu().numpy())

    return total_loss / len(loader), np.array(all_predictions), np.array(all_actuals)

# ============================================================================
# STEP 12: SMAPE Calculation
# ============================================================================
def calculate_smape(actual, predicted):
    """Calculate Symmetric Mean Absolute Percentage Error"""
    actual = np.array(actual).flatten()
    predicted = np.array(predicted).flatten()

    numerator = np.abs(predicted - actual)
    denominator = (np.abs(actual) + np.abs(predicted)) / 2

    mask = denominator != 0
    smape = np.zeros_like(numerator)
    smape[mask] = numerator[mask] / denominator[mask]

    return np.mean(smape) * 100

# ============================================================================
# STEP 13: Train the Model
# ============================================================================
print("\n" + "="*70)
print("STARTING TRAINING")
print("="*70)

best_val_loss = float('inf')
training_history = {
    'train_loss': [],
    'val_loss': [],
    'val_smape': []
}

for epoch in range(config.num_epochs):
    print(f"\n{'='*70}")
    print(f"Epoch {epoch + 1}/{config.num_epochs}")
    print(f"{'='*70}")

    train_loss = train_epoch(model, train_loader, optimizer, criterion, scheduler, config.device)
    val_loss, val_preds, val_actuals = validate(model, val_loader, criterion, config.device)

    # Convert back from log space for SMAPE calculation
    val_preds_original = np.expm1(val_preds)
    val_actuals_original = np.expm1(val_actuals)

    # Calculate SMAPE
    smape = calculate_smape(val_actuals_original, val_preds_original)

    training_history['train_loss'].append(float(train_loss))
    training_history['val_loss'].append(float(val_loss))
    training_history['val_smape'].append(float(smape))

    print(f"\nResults:")
    print(f"  Train Loss: {train_loss:.4f}")
    print(f"  Val Loss: {val_loss:.4f}")
    print(f"  Val SMAPE: {smape:.2f}%")

    # Save best model
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        print(f"\n  ✓ New best model! Saving...")

        os.makedirs(config.model_save_path, exist_ok=True)

        # Save model weights and configuration
        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'scheduler_state_dict': scheduler.state_dict(),
            'train_loss': train_loss,
            'val_loss': val_loss,
            'val_smape': smape,
            'config': {
                'model_name': config.model_name,
                'max_length': config.max_length,
                'dropout': config.dropout
            }
        }, f"{config.model_save_path}/best_model.pt")

        # Save tokenizer
        tokenizer.save_pretrained(config.model_save_path)

        # Save training history
        with open(f"{config.model_save_path}/training_history.json", 'w') as f:
            json.dump(training_history, f, indent=2)

    gc.collect()
    torch.cuda.empty_cache()

# ============================================================================
# STEP 14: Save Final Summary
# ============================================================================
print("\n" + "="*70)
print("TRAINING COMPLETED!")
print("="*70)

print(f"\nBest Validation Loss: {best_val_loss:.4f}")
print(f"Best Validation SMAPE: {min(training_history['val_smape']):.2f}%")

print(f"\nTraining History:")
for i, (tl, vl, vs) in enumerate(zip(training_history['train_loss'],
                                       training_history['val_loss'],
                                       training_history['val_smape'])):
    print(f"  Epoch {i+1}: Train Loss={tl:.4f}, Val Loss={vl:.4f}, Val SMAPE={vs:.2f}%")

print(f"\nModel saved at: {config.model_save_path}/")
print(f"Files saved:")
print(f"  - best_model.pt (model weights and config)")
print(f"  - tokenizer files")
print(f"  - training_history.json")

print("\n✓ Ready for inference!")
print("  Next: Run Script 2 to evaluate on sample_test.csv")
print("  Then: Run Script 3 to predict on test.csv")
